[metadata]
name = "dfint localization hook offsets"
version = "50.05 itch.io win64"
checksum = 0x63b61266

[offsets]
# translation
string_copy = 0xB560
string_copy_n = 0xB580
string_append_n = 0xB6C0
addst = 0x782190
addst_top = 0x7822E0
addcoloredst = 0x781DC0
addst_flag = 0x781EA0
addst_template = 0x96BB90
# search
standardstringentry = 0x87C1D0
simplify_string = 0x359F70
upper_case_string = 0x35A2B0
lower_case_string = 0x35A110
capitalize_string_words = 0x35A450
capitalize_string_first_word = 0x35A6D0
# ttf
addchar = 0x55D30
addchar_top = 0xE9D10
add_texture = 0xE7E020
gps_allocate = 0x5C0120
cleanup_arrays = 0x5BFF40
screen_to_texid = 0x5B81B0
screen_to_texid_top = 0x5B83A0
# game state
loading_world_new_game_loop = 0x9F8A60
loading_world_continuing_game_loop = 0x5645B0
loading_world_start_new_game_loop = 0x562930
menu_interface_loop = 0x167490
