[metadata]
name = "dfint localization hook offsets"
version = "50.04 steam win64"
checksum = 0x63a2a9ad

[offsets]
# translation
string_copy = 0xB5B0
string_copy_n = 0xB5D0
string_append = 0xB380
string_append_0 = 0xB3A0
string_append_n = 0xB710
convert_ulong_to_string = 0x35BC60
addst = 0x784C60
addst_top = 0x784DB0
addcoloredst = 0x784890
addst_flag = 0x784970
addst_template = 0x96E710
# search
standardstringentry = 0x87ED50
simplify_string = 0x35C7A0
upper_case_string = 0x35CAE0
lower_case_string = 0x35C940
capitalize_string_words = 0x35CC80
capitalize_string_first_word = 0x35CF00
# ttf
addchar = 0x55D80
addchar_top = 0xE9D60
add_texture = 0xE827F0
gps_allocate = 0x5C2AB0
cleanup_arrays = 0x5C28D0
screen_to_texid = 0x5BAB40
screen_to_texid_top = 0x5BAD30
# game state
loading_world_new_game_loop = 0x9FD2E0
loading_world_continuing_game_loop = 0x566F40
loading_world_start_new_game_loop = 0x5652C0
menu_interface_loop = 0x1678A0
